#!/bin/sh
mysql -P 3306 -uroot -p${MARIADB_ROOT_PASSWORD} -e "CREATE DATABASE ${WORDPRESS_DB_NAME}";
mysql -P 3306 -uroot -p${MARIADB_ROOT_PASSWORD} -e "CREATE USER '${WORDPRESS_DB_USER}'@'%' IDENTIFIED BY '${WORDPRESS_DB_PASSWORD}'";
mysql -P 3306 -uroot -p${MARIADB_ROOT_PASSWORD} -e "GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER,CREATE TEMPORARY TABLES,INDEX,LOCK TABLES ON ${WORDPRESS_DB_NAME}.* TO '${WORDPRESS_DB_USER}'@'%';";
