apiVersion: v2
name: wordpress
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: mariadb
    version: "19.1.0"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mariadb.enabled
  - name: redis
    version: "20.1.4"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
