apiVersion: v2
name: wordpress
description: A Helm chart for Wordpress on Kubernetes with NGINX and PHP-FPM
type: application
version: 0.1.34
appVersion: "6.7.2"
dependencies:
  - name: mariadb
    version: "21.0.2"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mariadb.enabled
  - name: redis
    version: "21.2.10"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
