apiVersion: v2
name: wordpress
description: A Helm chart for Wordpress on Kubernetes with NGINX and PHP-FPM
type: application
version: 0.1.28
appVersion: "6.7.2"
dependencies:
  - name: mariadb
    version: "20.5.5"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mariadb.enabled
  - name: redis
    version: "21.1.5"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
