apiVersion: v2
name: wordpress
description: A Helm chart for Wordpress on Kubernetes with NGINX and PHP-FPM
type: application
version: 0.1.0
appVersion: "6.2.2"
dependencies:
  - name: mariadb
    version: "19.1.0"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mariadb.enabled
  - name: redis
    version: "20.2.1"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
