apiVersion: v2
name: wordpress
description: A Helm chart for Wordpress on Kubernetes with NGINX and PHP-FPM
type: application
version: 0.1.39
appVersion: "6.8.3"
dependencies:
  - name: mariadb
    version: "23.2.4"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mariadb.enabled
  - name: redis
    version: "23.2.12"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
