apiVersion: v2
name: wordpress
description: A Helm chart for Wordpress on Kubernetes with NGINX and PHP-FPM
type: application
version: 0.1.18
appVersion: "6.7.1"
dependencies:
  - name: mariadb
    version: "20.4.1"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mariadb.enabled
  - name: redis
    version: "20.11.0"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled
