nameOverride: ""
fullnameOverride: ""

persistence:
  enabled: true
  storageClassName: "rook-cephfs" #ReadWriteMany support
  size: "10Gi"
  existingPvc: ""

wordpress:
  url: &url "wp-test.wordpress.smartcommunitylab.it"
  title: "wp-test"
  admin:
    username: "admin"
    password: "admin"
    email: "wp-test@test.local"
  database:
    name: "wptest"
    tablePrefix: "test"
    auth:
      username: "admin"
      password: "admin"
      existingSecret:
        enabled: false
        name: ""
        usernameKey: ""
        passwordKey: ""
    external: 
      enabled: false
      host: ""
  extraEnv: {}

ingress:
  enabled: true
  className: "nginx"
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
  hosts:
    - host: *url
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: wp-cert
      hosts:
        - *url

nginx:
  replicaCount: 1
  confsOverride:
    maxBodySize: 100M
  serviceAccount:
    create: true
    automount: false
    annotations: {}
    name: "nginx"
  image:
    repository: nginxinc/nginx-unprivileged
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "alpine"
  imagePullSecrets: []
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    fsGroup: 82
    runAsNonRoot: true
    runAsUser: 82
    runAsGroup: 82
  securityContext:
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    allowPrivilegeEscalation: false
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      memory: "1024Mi"
      cpu: "2"
    requests:
      memory: "512Mi"
      cpu: "512m"
  livenessProbe:
    httpGet:
      path: /readme.html
      port: http
    initialDelaySeconds: 60
    timeoutSeconds: 10
  readinessProbe:
    httpGet:
      path: /readme.html
      port: http
    initialDelaySeconds: 20
    timeoutSeconds: 10
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  # Additional volumes on the output Deployment definition.
  volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false
  # Additional volumeMounts on the output Deployment definition.
  volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true
  nodeSelector: {}
  tolerations: []
  affinity: {}

php:
  replicaCount: 1
  iniConfigOverride:
    memoryLimit: 128M
    maxExecutionTime: 300
    postMaxSize: 100M
    maxInputTime: 90
    uploadMaxFileSize: 100M
  poolConfigOverride:
    pm: "dynamic"
    pmMaxChildren: "24"
    pmStartServers: "6"
    pmMinSpareServers: "6"
    pmMaxSpareServers: "18"
    pmStatusPath: /status
  image:
    repository: smartcommunitylab/wordpress
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "redis-latest"
  imagePullSecrets: []
  serviceAccount:
    create: true
    automount: false
    annotations: {}
    name: "php"
  podAnnotations: {}
  podLabels: {}
  podSecurityContext:
    fsGroup: 82
    runAsNonRoot: true
    runAsUser: 82
    runAsGroup: 82
  securityContext:
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    allowPrivilegeEscalation: false
  service:
    type: ClusterIP
    port: 9000
  resources: 
    limits:
      memory: "1024Mi"
      cpu: "2"
    requests:
      memory: "512Mi"
      cpu: "512m"
  livenessProbe:
    exec:
      command:
        - php-fpm-healthcheck
        - --listen-queue=10 # fails if there are more than 10 processes waiting in the fpm queue
    initialDelaySeconds: 25
    periodSeconds: 30
  readinessProbe:
    exec:
      command:
        - php-fpm-healthcheck # a simple ping since this means it's ready to handle traffic
    initialDelaySeconds: 25
    periodSeconds: 15
  startupProbe:
    tcpSocket:
      port: 9000
    initialDelaySeconds: 25
    periodSeconds: 10
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  # Additional volumes on the output Deployment definition.
  volumes: []
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false
  # Additional volumeMounts on the output Deployment definition.
  volumeMounts: []
  # - name: foo
  #   mountPath: "/etc/foo"
  #   readOnly: true
  nodeSelector: {}
  tolerations: []
  affinity: {}
  exporter:
    enabled: true
    image:
      repository: smartcommunitylab/php-fpm_exporter
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: "nonroot"
    serviceMonitor:
      enabled: true
    securityContext:
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      allowPrivilegeEscalation: false
    resources: 
      limits:
        memory: "64Mi"
        cpu: "200m"
      requests:
        memory: "32Mi"
        cpu: "100m"

mariadb:
  enabled: true
  initdbScriptsConfigMap: "mariadb-init-script-configmap"
  primary:
    resources:
      requests:
        cpu: 1
        memory: 512Mi
      limits:
        cpu: 3
        memory: 1024Mi
    extraEnvVarsSecret: "wp-test-db-vars"
    persistence:
      enabled: true
      existingClaim: ""
      subPath: ""
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 8Gi
  auth:
    database: ""

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: false
    sentinel: false
    existingSecret: ""
    existingSecretPasswordKey: ""
  master:
    persistence:
      enabled: false

debug:
  enabled: true
  image:
    repository: wordpress
    pullPolicy: IfNotPresent
    tag: "cli-php8.2"
  imagePullSecrets: []
  serviceAccount:
    create: true
    automount: false
    annotations: {}
    name: "debug"
  resources:
    limits:
      memory: "512Mi"
      cpu: "1"
    requests:
      memory: "64Mi"
      cpu: "100m"
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podSecurityContext:
    fsGroup: 82
    runAsNonRoot: true
    runAsUser: 82
    runAsGroup: 82
  securityContext:
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    allowPrivilegeEscalation: false

jobs:
  serviceAccount:
    create: true
    automount: false
    annotations: {}
    name: "jobs"
  initialize:
    enabled: true
  backup:
    cron: "0 0 * * *"
    tempStorageSize: 1024Mi
    azure:
      enabled: true
      image:
        repository: peterdavehello/azcopy
        tag: 10
      resources:
        limits:
          memory: "4096Mi"
          cpu: "1"
        requests:
          memory: "64Mi"
          cpu: "100m"
    s3:
      enabled: false
    pvc:
      enabled: false
  update:
    enabled: true
    cron: "0 1 * * *"
    plugins: true
    themes: true
    languages: true
    core: true
  plugins:
    enabled: true
    deleteUnused: true
    w3tc:
      enabled: true
  common:
    ttlSecondsAfterFinished: 86400
    image:
      repository: wordpress
      pullPolicy: IfNotPresent
      tag: "cli-php8.2"
    imagePullSecrets: []
    serviceAccount:
      create: true
      automount: false
      annotations: {}
      name: "debug"
    resources:
      limits:
        memory: "256Mi"
        cpu: "1"
      requests:
        memory: "64Mi"
        cpu: "100m"
    nodeSelector: {}
    tolerations: []
    affinity: {}
    podSecurityContext:
      fsGroup: 82
      runAsNonRoot: true
      runAsUser: 82
      runAsGroup: 82
    securityContext:
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      allowPrivilegeEscalation: false

