{{- if .Values.debug.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wordpress.serviceAccountName" (dict "root" . "component" "debug") }}
  labels:
    {{- include "wordpress.labels" (dict "root" . "component" "debug") | nindent 4 }}
  {{- with .Values.debug.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.debug.serviceAccount.automount }}
{{- end }}
