{{- if .Values.jobs.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wordpress.serviceAccountName" (dict "root" . "component" "jobs") }}
  labels:
    {{- include "wordpress.labels" (dict "root" . "component" "jobs") | nindent 4 }}
  {{- with .Values.jobs.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.jobs.serviceAccount.automount }}
{{- end }}
