apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" (dict "root" . "component" "nginx") }}
  labels:
    {{- include "wordpress.labels" (dict "root" . "component" "nginx") | nindent 4 }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "wordpress.selectorLabels" (dict "root" . "component" "nginx") | nindent 4 }}
