{{- if .Values.php.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wordpress.serviceAccountName" (dict "root" . "component" "php") }}
  labels:
    {{- include "wordpress.labels" (dict "root" . "component" "php") | nindent 4 }}
  {{- with .Values.php.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.php.serviceAccount.automount }}
{{- end }}
