{{- if .Values.jobs.initialize.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "wordpress.fullname" (dict "root" . "component" "init-job") }}
  labels:
    {{- include "wordpress.labels" (dict "root" . "component" "init-job") | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "wordpress.fullname" (dict "root" . "component" "init-job") }}
      labels:
        {{- include "wordpress.labels" (dict "root" . "component" "init-job") | nindent 8 }}
    spec:
      {{- with .Values.jobs.common.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wordpress.serviceAccountName" (dict "root" . "component" "php") }}
      securityContext:
        {{- toYaml .Values.jobs.common.podSecurityContext | nindent 8 }}
      containers:
      - name: wordpress-init
        securityContext:
          {{- toYaml .Values.jobs.common.securityContext | nindent 12 }}
        image: "{{ .Values.jobs.common.image.repository }}:{{ .Values.jobs.common.image.tag | default .Chart.AppVersion }}"
        command: ['/bin/sh', '/etc/init/init-script.sh']
        env:
          - name:  WORDPRESS_DB_HOST
          {{- if .Values.wordpress.database.external.enabled }}
            value: {{ .Values.wordpress.database.external.host | quote }}
          {{- else }}
            value: {{ (printf "%s-%s:%s" .Release.Name "mariadb" "3306") | quote }}
          {{- end }}
        envFrom:
          - secretRef:
              name: {{ .Release.Name }}-db-vars
          - secretRef:
              name: {{ .Release.Name }}-wordpress-site-vars
          - configMapRef:
              name: {{ .Release.Name }}-wordpress-vars
        resources:
          {{- toYaml .Values.jobs.common.resources | nindent 12 }}
        volumeMounts:
        {{- if .Values.persistence.enabled }}
          - name: shared-dir
            mountPath: /var/www/html/
        {{- end }}
          - name: init-script
            mountPath: /etc/init/
      volumes:
      {{- if .Values.persistence.enabled }}
        - name: shared-dir
          persistentVolumeClaim:
            claimName: {{ include "wordpress.pvcName" . }}
      {{- end }}
        - name: init-script
          configMap:
            name: {{ .Release.Name }}-wordpress-scripts
            items:
              - key: init-script.sh
                path: init-script.sh
      restartPolicy: OnFailure
      dnsPolicy: ClusterFirst
{{- end -}}
