{{- if .Values.jobs.plugins.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "wordpress.fullname" (dict "root" . "component" "plugins") }}
  labels:
    {{- include "wordpress.labels" (dict "root" . "component" "plugins") | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      name: {{ include "wordpress.fullname" (dict "root" . "component" "plugins") }}
      labels:
        {{- include "wordpress.labels" (dict "root" . "component" "plugins") | nindent 8 }}
    spec:
      {{- with .Values.jobs.common.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wordpress.serviceAccountName" (dict "root" . "component" "jobs") }}
      securityContext:
        {{- toYaml .Values.jobs.common.podSecurityContext | nindent 8 }}
      containers:
      - name: wordpress-plugins
        securityContext:
          {{- toYaml .Values.jobs.common.securityContext | nindent 12 }}
        image: "{{ .Values.jobs.common.image.repository }}:{{ .Values.jobs.common.image.tag | default .Chart.AppVersion }}"
        command: ['/bin/sh', '/etc/plugins/plugins-script.sh']
        env:
          - name:  WORDPRESS_DB_HOST
          {{- if .Values.wordpress.database.external.enabled }}
            value: {{ .Values.wordpress.database.external.host | quote }}
          {{- else }}
            value: {{ (printf "%s-%s:%s" .Release.Name "mariadb" "3306") | quote }}
          {{- end }}
          {{- if and .Values.redis.enabled .Values.jobs.plugins.w3tc.enabled }}
          - name: REDIS_HOST
            value: {{ (printf "%s-%s" .Release.Name "redis-master") | quote }}
          - name: REDIS_PORT
            value: {{ (printf "%s" "6379") | quote }}
          {{- end }}
        envFrom:
          - secretRef:
              name: db-vars
          - secretRef:
              name: {{ .Release.Name }}-wordpress-site-vars
          - configMapRef:
              name: {{ .Release.Name }}-wordpress-vars
        resources:
          {{- toYaml .Values.jobs.common.resources | nindent 12 }}
        volumeMounts:
        {{- if .Values.persistence.enabled }}
          - name: shared-dir
            mountPath: /var/www/html/
        {{- end }}
          - name: plugins
            mountPath: /etc/plugins/
      volumes:
      {{- if .Values.persistence.enabled }}
        - name: shared-dir
          persistentVolumeClaim:
            claimName: {{ include "wordpress.pvcName" . }}
      {{- end }}
        - name: plugins
          configMap:
            name: {{ .Release.Name }}-wordpress-plugins-scripts
            items:
              - key: plugins-script.sh
                path: plugins-script.sh
      restartPolicy: OnFailure
      dnsPolicy: ClusterFirst
{{- end -}}
