apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-vars
type: kubernetes.io/Opaque
data:
  WORDPRESS_DB_NAME: {{ .Values.wordpress.database.name | b64enc }}
  WORDPRESS_TABLE_PREFIX: {{ .Values.wordpress.database.tablePrefix | b64enc }}
{{- if not (.Values.wordpress.database.auth.existingSecret.enabled) }}
  WORDPRESS_DB_USER: {{ .Values.wordpress.database.auth.username | b64enc }}
  WORDPRESS_DB_PASSWORD: {{ .Values.wordpress.database.auth.password | b64enc }}
{{- end }}
