apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-wordpress-site-vars
type: kubernetes.io/Opaque
data:
  WORDPRESS_ADMIN_USERNAME: {{ .Values.wordpress.admin.username | b64enc }}
  WORDPRESS_ADMIN_PASSWORD: {{ .Values.wordpress.admin.password | b64enc }}
  WORDPRESS_ADMIN_EMAIL: {{ .Values.wordpress.admin.email | b64enc }}
