{{- if .Values.jobs.update.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-wordpress-update
data: {{ tpl (.Files.Glob "confs/wordpress/update-script.sh").AsConfig . | nindent 2 }}
{{- end -}}
